---
abstract: 'Be like ZAKAME'
author:
  - 'Zak B. Elep <zakame@cpan.org>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.6.7, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-BeLike-ZAKAME
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Task::BeLike::ZAKAME:
    file: lib/Task/BeLike/ZAKAME.pm
    version: 0.01
requires:
  App::Ack: 0
  App::cpanoutdated: 0
  App::ph: 0
  CPAN::Mini: 0
  CPAN::Uploader: 0
  Minilla: 0
  Moo: 0
  Perl::Critic: 0
  Perl::Tidy: 0
  Reply: 0
  Version::Next: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/zakame/Task-BeLike-ZAKAME/issues
  homepage: https://github.com/zakame/Task-BeLike-ZAKAME
  repository: git://github.com/zakame/Task-BeLike-ZAKAME.git
version: 0.01
x_contributors:
  - 'Zak B. Elep <zakame@zakame.net>'
